### PR TITLE
Import Error directly from transformers

### LINKED ISSUE #76: Build failure with mtl-2.3.1
The latest release `happstack-7.8.0.1` fails to build with `mtl-2.3.1` if `transformers < 0.6`:
```
$ cabal build -c 'mtl >= 2.3'
Build profile: -w ghc-9.4.4 -O1
In order, the following will be built (use -v for more details):
 - happstack-server-7.8.0.1 (lib) (first run)
...
[21 of 35] Compiling Happstack.Server.RqData ( src/Happstack/Server/RqData.hs, /Users/abel/tmp/happstack-server-7.8.0.1/dist-newstyle/build/x86_64-osx/ghc-9.4.4/happstack-server-7.8.0.1/build/Happstack/Server/RqData.o, /Users/abel/tmp/happstack-server-7.8.0.1/dist-newstyle/build/x86_64-osx/ghc-9.4.4/happstack-server-7.8.0.1/build/Happstack/Server/RqData.dyn_o ) [Control.Monad.Trans package changed]

src/Happstack/Server/RqData.hs:186:31: error:
    • No instance for (Control.Monad.Trans.Error.Error (Errors String))
        arising from the 'deriving' clause of a data type declaration
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    • When deriving the instance for (MonadPlus RqData)
    |
186 |     deriving (Functor, Monad, MonadPlus, Applicative, Alternative, MonadReader RqEnv )
    |        
```
Lifted from: https://github.com/Happstack/happstack-server/pull/74#issuecomment-1367788379

Suggested path of action:
1. Fix this and release as 7.8.0.2.
2. Revise 7.8.0 and 7.8.0.1 on hackage with `mtl < 2.3`.

### PR DESCRIPTION
**Pull request by ysangkok**
Fixes #76.

Tested on GHC 9.4.3 and 9.2.5:
- Constraint solving fails as expected: `cabal build -c 'mtl<2.3' -c 'transformers>0.6'`
- Passes: `cabal test -c 'mtl>=2.3' -c 'transformers>=0.6'`
- Passes: `cabal test -c 'mtl>=2.3' -c 'transformers<0.6'`
- Passes: `cabal test -c 'mtl<2.3' -c 'transformers<0.6'`

I opted for just having consistent version checking on the `transformers`
package version, instead of having branching on both. I regard branching on
transformers as better, since that is the package that removed the `Error`
module.

I previously thought that using `mtl-2.3` implies using `transformers-0.6`,
since the the reverse is true. But that was mistaken, thanks for catching that
@andreasabel.

### CODE REVIEW

**Review by andreasabel — APPROVED** [review]
Great.  (Approved, trusting the tests worked as described.)

**Comment by stepcut** [comment]
Thanks for the PR -- sorry about the delay. This is on hackage has happstack-server 7.8.0.2 now.
